language: cpp
sudo: required

cache:
 - apt

before_install:
  - sudo apt-get purge -qq -y
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
  - sudo add-apt-repository -y ppa:zosrothko/poco 
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libpoco-dev g++-4.8
  - sudo apt-get install -qq -y  sloccount cppcheck
  - sudo ldconfig  
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"

#services:
  

notifications:
  slack: 
    rooms:
      - kampbell:v4ARuptk0ETzwUsKDdV6Gspb#iso-8583


env:
  global: TEST_NAME=""

before_script:
 - uname -a
 - echo ${TEST_NAME}
 - dpkg -L libpoco-dev

matrix:
  include:
    - env:    TEST_NAME="gcc (make)"
      compiler: gcc
      script:
      - make -C cpp/make
