version: 1.0.{build}-{branch}

cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Poco\1.6.1
  - C:\Progra~1\Cppcheck\cppcheck

pull_requests:
  do_not_increment_build_number: true

platform: 
  - Win32
#  - x64

configuration:
  - debug
  - release
 
environment:
  POCO: C:\Poco\1.6.1
  
  matrix:
    - builder: make

    - builder: msbuild
      vsver: 120
      vc: x86

      
#matrix:
#  fast_finish: true  

install:
#  - c:\cygwin\setup-x86.exe -B -q -n -N -d -l c:\cygwin -R c:\cygwin -s http://mirror.csclub.uwaterloo.ca/cygwin  -P gcc
  
  - set PATH=C:\ProgramData\chocolatey\bin;%PATH%
  - set PATH=C:\cygwin\bin;%PATH%
  - ps: |
        if (Test-Path "C:\Poco\1.6.1") {
           echo "usingC:\Poco\1.6.1 from cache"
        } else {
           echo "downloading VS2013.Poco.1.6.1.x86.msi"
           mkdir msi
           appveyor DownloadFile https://github.com/pocoproject/distro/releases/download/Poco-1.6.1/VS2013.Poco.1.6.1.x86.msi -Filename msi\VS2013.Poco.1.6.1.x86.msi
           & cmd /c start /wait  msiexec /a msi\VS2013.Poco.1.6.1.x86.msi /quiet /qn /norestart  TARGETDIR=C:\ /log install.log
        }
#           c:\cygwin\bin\find.exe $env:POCO
  - ps: |
        if (!(Test-Path "c:\Progra~1\Cppcheck\cppcheck")) {
            echo "usingc:\Progra~1\Cppcheck\cppcheck from cache"
        } else {
        }

before_build:
  - set PATH=%POCO%\bin;%PATH%
  - set
  - ps: |
      if ($env:builder -eq "msbuild")
      {
        if ($env:vsver -eq "120")
        {
          & "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %vc%
        }
        if ($env:vsver -eq "140")
        {
          & "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %vc%
        }
      }
  
build:
  
build_script:
  - ps: |
      if ($env:builder -eq "msbuild")
      {
        $verbosity='minimal';
        $logger='C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll';
        msbuild /t:build /logger:$logger /m /nologo /v:$verbosity /p:Configuration=$env:Configuration /p:Platform=$env:platform cpp\vs2013\ISO-8583.sln
      }
      if ($env:builder -eq "make")
      {
         $env:POCOINC=cygpath "$env:POCO"/inc
         $env:POCOLIB=cygpath "$env:POCO"/lib         
         make.exe -C cpp/make )
      }
   
   
after_build:  


test:
  assemblies:
    - '**\*.test.exe'
    - '**\*.testd.exe'
    
  categories:
    - UI
    - E2E

before_test:
  - echo before_test
  
after_test:
  - echo after_test
#  - c:\Progra~1\Cppcheck\cppcheck --force --quiet --inline-suppr -j2 .
  - ps: |
      $line='-------------------------------------------------------------------------------------';
      $find='c:\cygwin\bin\find.exe';
      $arg1=". -type f -name '*.cpp' -exec c:\cygwin\bin\grep -n -H ";
      $arg2=" {} ;"
      
      Write-Host -ForegroundColor Yellow $line;
      $word='FIXME'
      Start-Process -NoNewWindow -Wait -FilePath $find -Args "$arg1 $word $arg2" -RSO "cout" -RSE "cerr"; 
      gc cout; gc cerr;
      Write-Host;Write-Host;

      Write-Host -ForegroundColor Yellow $line;
      $word='TODO'
      Start-Process -NoNewWindow -Wait -FilePath $find -Args "$arg1 $word $arg2" -RSO "cout" -RSE "cerr"; 
      gc cout; gc cerr;
      Write-Host;Write-Host;

      Write-Host -ForegroundColor Yellow $line;
      $word='HACK'
      Start-Process -NoNewWindow -Wait -FilePath $find -Args "$arg1 $word $arg2" -RSO "cout" -RSE "cerr"; 
      gc cout; gc cerr;
      Write-Host;Write-Host;


test_script:
  - ps: |
        [string]$suffix=''
        if ($env:Configuration -eq "debug") { $suffix='d';  }
        Write-host test in $env:Configuration
        
        $path = ".\cpp\vs2013\$env:configuration\ISO-8583-DTT-Test$suffix.exe";
        $process = Start-Process -NoNewWindow -Wait -FilePath $path -Args "-all" -RSO "cout" -RSE "cerr"
        gc cout; gc cerr;
        
        $path = ".\cpp\vs2013\$env:configuration\ISO-8583-DTE-1987-Test$suffix.exe";
        $process = Start-Process -NoNewWindow -Wait -FilePath $path -Args "-all" -RSO "cout" -RSE "cerr"
        gc cout; gc cerr;
        
        $path = ".\cpp\vs2013\$env:configuration\ISO-8583-MSG-1987-Test$suffix.exe";
        $process = Start-Process -NoNewWindow -Wait -FilePath $path -Args "-all" -RSO "cout" -RSE "cerr"
        gc cout; gc cerr;
      
  
on_success:
  - echo on_success

on_failure:
  - echo on_failure

on_finish:
  - echo on_finish


notifications:
  - provider: Slack
    auth_token:
      secure: xoOlP1UHshqjvh/INwMcNhZ5UHsTVKLGY5maTSjaxDc0fvRwoWIdYvY/CofQEuy2wOIBQK4eLD+tA0xG78ZgqQ==
    channel: iso-8583
